### ISSUE TITLE
Initialize Laravel Project

### ISSUE THREAD

**Issue by waynetheisinger** [waynetheisinger/saaseller#1]
**Description:**  
- Set up a new Laravel project.  
- Configure `.env` for local development.  
- Install essential dependencies (`spatie/laravel-permission`, `laravel/sanctum`, etc.).  
- Set up database migrations.

**Tasks:**  

- [x] - Install Laravel.  
- [x] - Set up `.env` file.  
- [x] - Configure database.  
- [x] - Install required packages.  

**Acceptance Criteria:**  

- [x] - Laravel project is up and running locally.  
- [x] - Database migrations are working.
