### ISSUE TITLE
Implement API Versioning

### ISSUE THREAD

**Issue by waynetheisinger** [waynetheisinger/saaseller#11]
- **Priority:** P2  
- **Size:** XS  
- **Estimate:** 2  

**Description:**  
Introduce versioning (`/api/v1/`) for all API endpoints.

**Tasks:**  

- [ ] - Add version prefix to routes.  
- [ ] - Ensure backward compatibility.  

**Acceptance Criteria:**  

- [ ] - API versioning is enforced.
