### ISSUE TITLE
Write Unit and Feature Tests

### ISSUE THREAD

**Issue by waynetheisinger** [waynetheisinger/saaseller#13]
- **Priority:** P0  
- **Size:** L  
- **Estimate:** 8  

**Description:**  
Write tests for authentication, middleware, and RBAC policies.

**Tasks:**  

- [ ] - PHPUnit tests for authentication.  
- [ ] - Middleware and policy tests.  

**Acceptance Criteria:**  

- [ ] - All tests pass successfully.
