### ISSUE TITLE
Issue 14: Set Up CI/CD Pipeline

### ISSUE THREAD

**Issue by waynetheisinger** [waynetheisinger/saaseller#14]
- **Priority:** P1  
- **Size:** M  
- **Estimate:** 5  

**Description:**  
Automate testing and deployment using GitHub Actions.

**Tasks:**  

- [ ] - Configure `.github/workflows/ci.yml`.  
- [ ] - Automate testing and deployments.  

**Acceptance Criteria:**  

- [ ] - CI/CD pipeline runs on push and pull requests.
