### ISSUE TITLE
Add API Monitoring

### ISSUE THREAD

**Issue by waynetheisinger** [waynetheisinger/saaseller#15]
- **Priority:** P2  
- **Size:** M  
- **Estimate:** 4  

**Description:**  
Set up API monitoring tools like Sentry and Laravel Telescope.

**Tasks:**  

- [ ] - Install Sentry for error tracking.  
- [ ] - Enable Laravel Telescope.  

**Acceptance Criteria:**  

- [ ] - Monitoring tools are tracking API calls and errors.
