### ISSUE TITLE
Partner Dashboard Endpoints

### ISSUE THREAD

**Issue by waynetheisinger** [waynetheisinger/saaseller#8]
- **Priority:** P1  
- **Size:** L  
- **Estimate:** 8  

**Description:**  
Create API endpoints for partners to manage accounts.

**Tasks:**  

- [ ] - `GET /api/v1/partner/accounts`  
- [ ] - `POST /api/v1/partner/accounts/create`  
- [ ] - `PATCH /api/v1/partner/accounts/{id}`  

**Acceptance Criteria:**  

- [ ] - Endpoints allow partners to manage sub-accounts.
